[clean_data]
git-tree-sha1 = "91a6fbe6a8cede44ea4252afdeb6303d81b4dafa"

    [[clean_data.download]]
    sha256 = "ffb0ceac8e3ec151f376b8e8875cc8a6a63b4ade128a11117bc00c0b66f9736b"
    url = "https://github.com/pat-alt/TrillionDollarWords.jl/releases/download/artifacts-latest/91a6fbe6a8cede44ea4252afdeb6303d81b4dafa.tar.gz"
