name = "TrillionDollarWords"
uuid = "d66529d5-f4f4-49d9-a69b-da67f5535f0a"
authors = ["Patrick Altmeyer"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
